### ISSUE TITLE
Python initialization fails when env vars not set

### ISSUE THREAD

**Issue by jesumyip** [ubiqsecurity/ubiq-python#1]
Using the latest version of the Python library, and Python 3.9, if I run the following code:

import ubiq_security as ubiq
ubiq_creds = ubiq.credentials()
print(ubiq_creds.get_access_key_id())
encrypted_data = ubiq.encrypt(ubiq_creds, "Hi there")

The last line will crash with "AttributeError: 'NoneType' object has no attribute 'encode'.

Looking at the ubiq Python module source code, it looks like the issue is when the environment variables for storing the API keys are not defined, the module returns a Python None type to the caller. A better way to handle this would be to raise an error.

**Comment by johntyner** [comment]
@jesumyip Thanks for catching this and raising the issue. Apologies for the delay in getting to it. I've posted #2 to address it.
